root = "."
tmp_dir = "build"

[build]
cmd = "go build -o ./build/sheaf ./sheaf"
entrypoint = "./build/sheaf"
include_ext = ["go"]
exclude_dir = ["build", "static"]
exclude_regex = ["_test\\.go"]

[[build.rules]]
name = "templ"
include_ext = ["templ"]
cmd = "go tool templ generate"

[[build.rules]]
name = "sqlc"
include_ext = ["sql"]
cmd = "go tool sqlc generate"

[proxy]
enabled = true
proxy_port = 8090
app_port = 8080
